language: ruby
rvm:
- 2.1
script: bundle exec rake
bundler_args: "--binstubs"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/usnationalarchives/capstone-grs.git
  - secure: bW414btpFaP0G3gyexQ9n+RcCxK4BmydpRUFsuKfXjm2+IXFEgbfDXWGJ4zUM4WWbjz2pbmjKGmfd8DsY1AIqXG4M8OV0VCt84e8g8h++JqroCp8A8H0cKudxGjAQ4rfGkDMcSLVpElJeyF3K0u/dAlCZrH77BdgOAMqoTt8BwlbaIf1p2Y/dRcDJWx++5A8E9NifOZ5UMVNQBYg1s4RIXsQoOmL+IgrR2+LhgU4HM6SOFbB81HWt9pSpxj73GCIPHaI2pqp69iQ2Awrlfx9UN/i9XO6ndjg4nh46nIRXoTXuJKCt4lNnZI+3T+261SMG1NGctBTumuQN43J5KOGf07DFsGEz9Sd5V19UVP9JO8578iKZ0TEKzLtEoHL0k71BKzrqb7uqUEP/dD2qyq2aON5p4pJLI6zTg2isu+VLWXFoXnfQ0umvht2sYR9CHs+VCXZLcx/+A44IxdfIaH5PJSmEQCJqhAPRyPQNJR1lnRVB+QwrJmQswPS5JFMvvEmvrY04/wwAPnWazq0EZHlZ7+en67CAG3kgoAyIY0ZKZhIaGXsOkkmLtvCtRq1xhVrkgSdDiWun06uOv3z0CE2r/QNcKuknd+e9b6aEq4rlLzCnm4aFvqFgZU0uODc9ZDTFn/KWRFHlIpydRgzwV9qo0UuN/oNYgM7H/NsUuRsG+s=
install:
- git config --global user.email "davidnaffis@gmail.com"
- git config --global user.name "naffis"
- travis_wait bundle install