language: ruby
rvm:
- 2.1
script: bundle exec rake
bundler_args: "--binstubs"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/usnationalarchives/capstone-grs.git
  - secure: 1+UH+913H6ETJahYs9K9z3a5yKan5XfAjb41hOmen+IMG+UHJuufp1R4r+UAGmnfrf9IlNBYUKDwEWbToeTQ4Kfxk8VeBnmjRiQw7lg/lTbCMG7REUUGkvL2QA7NSFTyozHbBeM/ZC2Om/Gzn/vIblO9XTn03P+fbpxTGy/txCgabq7nSYCNzuwjqf7kT6F5hwpDljvBMnXLK65tvFz5ScqG1i7Eompt9CvMMGBvAEmd6c3aww3RzkXDdiq4JuytJZ2Ek91vqkY+wGT5XjRoLqDdbYi4z1dNyBz2p9KRlJ3/xlz2a1duEahs8tovqC4do+2MYopP0SQdqGIxUn3FCQpFPuH9hWfdqanQHuR0RggafyCTxsPC3G7aNDHyv87sYJO/rltYUWGTZR7JQ7LSTeTFf26MaehiyaPFlox8zNOQ1Xzl7vw/Mr9OSxi+pFwVPHw1+0hs9IBnvtvPBW4pqnb2g18yWuk6Kr7mRPTOM0PmCB1S8igzQIU83seqKb7nFOriNZv2kefTOY2yTiBzP/3+TMuoMsMKs52mm6Fq6Ctcfia1UGA2LI1H8TJhZPKC7qKTwf+JD0NMphdK5N7NxfY2Q6k5KpS0TSYWXc9h18NIi1N79EPfYhsIq/EIyXrm0TCqA+77Wuuj4IelvY3rxR/bh3SEuvr92uYnUAL8oNA=
install:
- git config --global user.email "davidnaffis@gmail.com"
- git config --global user.name "naffis"
- travis_wait bundle install